version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3307:3306

  webapi:
    build:
      context: ./API.proj
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5239:80
    depends_on:
      - database

  razorpages:
    build:
      context: ./FrontRazor.proj/FrontRazor
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5238:80
    depends_on:
      - database
      - webapi
