version: '3'
services:
  database:
    image: mysql:8.0.31
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=restaurante
      - MYSQL_DATABASE=restaurante
    volumes:
      - ./volumes/dbdata:/var/lib/mysql

  webapi:
    build:
      context: ./API.proj
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5239:80
    depends_on:
      - database

  razorpages:
    build:
      context: ./FrontRazor.proj/FrontRazor
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5238:80
    depends_on:
      - database
      - webapi
